# Generated by Django 2.2.6 on 2019-10-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeclass', models.CharField(max_length=20, verbose_name='年级编号')),
                ('classname', models.CharField(max_length=50, verbose_name='年级')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='家庭住址')),
                ('studentid', models.CharField(max_length=18, verbose_name='学号')),
                ('nationality', models.CharField(blank=True, max_length=50, verbose_name='民族')),
                ('name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('genda', models.CharField(max_length=50, verbose_name='性别')),
                ('bithday', models.DateField(verbose_name='出生日期')),
                ('idcardno', models.CharField(max_length=20, verbose_name='身份证号')),
                ('stature', models.IntegerField(default=0, verbose_name='身高')),
                ('weight', models.FloatField(default=0, verbose_name='体重')),
                ('lungcapacity', models.IntegerField(default=0, verbose_name='肺活量')),
                ('fiftymeter', models.FloatField(default=0, verbose_name='50米')),
                ('standingbroadjump', models.FloatField(default=0, verbose_name='立定跳远')),
                ('sitandreach', models.FloatField(default=0, verbose_name='坐位体前屈')),
                ('middle_distancerun', models.FloatField(default=0, verbose_name='中长跑')),
                ('Oneminutesitups', models.IntegerField(default=0, verbose_name='一分钟仰卧起坐')),
                ('pull_ups', models.IntegerField(default=0, verbose_name='引体向上')),
                ('enter_date', models.DateField(verbose_name='入学时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
        ),
    ]
