# Generated by Django 2.2.6 on 2019-10-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='score',
            field=models.FloatField(default=0, verbose_name='总分'),
        ),
        migrations.AlterField(
            model_name='students',
            name='enter_date',
            field=models.DateField(blank=True, verbose_name='入学时间'),
        ),
    ]
