# Generated by Django 2.1.4 on 2019-10-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': '体能测试成绩', 'verbose_name_plural': '体能测试成绩'},
        ),
    ]
