# Generated by Django 2.2.6 on 2019-10-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191021_0238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': '体能测试成绩表', 'verbose_name_plural': '体能测试成绩表'},
        ),
        migrations.AlterField(
            model_name='students',
            name='genda',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=50, verbose_name='性别'),
        ),
    ]
