# Generated by Django 2.2.6 on 2019-10-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191021_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='专业班级')),
            ],
            options={
                'verbose_name': '专业班级表',
                'verbose_name_plural': '专业班级表',
            },
        ),
        migrations.AddField(
            model_name='students',
            name='testdatetime',
            field=models.CharField(blank=True, max_length=50, verbose_name='测试时间'),
        ),
        migrations.AddField(
            model_name='students',
            name='testsite',
            field=models.CharField(blank=True, max_length=50, verbose_name='测试场地'),
        ),
        migrations.AlterField(
            model_name='students',
            name='classname',
            field=models.CharField(max_length=50, verbose_name='专业班级'),
        ),
    ]
