# Generated by Django 2.2.6 on 2019-10-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191021_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDatetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testTime', models.CharField(max_length=100, verbose_name='测试时间')),
            ],
            options={
                'verbose_name': '测试时间',
                'verbose_name_plural': '测试时间',
            },
        ),
        migrations.CreateModel(
            name='TestSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=100, verbose_name='测试场地')),
            ],
            options={
                'verbose_name': '测试场地',
                'verbose_name_plural': '测试场地',
            },
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': '专业班级表', 'verbose_name_plural': '专业班级表ｓ'},
        ),
    ]
