# Generated by Django 2.2.6 on 2019-10-21 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191021_0322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': '专业班级表', 'verbose_name_plural': '专业班级表'},
        ),
    ]
