# Generated by Django 2.2.6 on 2019-10-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191021_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techerName', models.CharField(max_length=20, verbose_name='教师姓名')),
                ('techerGenda', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('mobileNo', models.CharField(max_length=20, verbose_name='手机号码')),
                ('officeNo', models.CharField(blank=True, max_length=20, verbose_name='座机号码')),
                ('office', models.CharField(blank=True, max_length=50, verbose_name='办公室')),
            ],
            options={
                'verbose_name': '教师信息表',
                'verbose_name_plural': '教师信息表',
            },
        ),
        migrations.RemoveField(
            model_name='students',
            name='testdatetime',
        ),
        migrations.RemoveField(
            model_name='students',
            name='testsite',
        ),
        migrations.AlterField(
            model_name='students',
            name='genda',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别'),
        ),
    ]
