# Generated by Django 2.2.6 on 2019-10-21 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191021_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='testdatetime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TestDatetime', verbose_name='测试教师'),
        ),
        migrations.AddField(
            model_name='students',
            name='testsite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TestSite', verbose_name='测试场地'),
        ),
        migrations.AddField(
            model_name='students',
            name='testtecher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TecherInfo', verbose_name='测试教师'),
        ),
    ]
