# Generated by Django 2.2.6 on 2019-10-21 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191021_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='testdatetime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TestDatetime', verbose_name='测试时间'),
        ),
    ]
