# Generated by Django 2.2.6 on 2019-10-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_testschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='bithday',
            field=models.DateField(null=True, verbose_name='出生日期'),
        ),
    ]
