# Generated by Django 2.2.6 on 2019-10-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191021_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='enrollment',
            field=models.DateField(blank=True, null=True, verbose_name='入学时间'),
        ),
    ]
