# Generated by Django 2.2.6 on 2019-10-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191021_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='testdatetime',
        ),
        migrations.RemoveField(
            model_name='students',
            name='testsite',
        ),
        migrations.RemoveField(
            model_name='students',
            name='testtecher',
        ),
    ]
