# Generated by Django 2.2.6 on 2019-10-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191021_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='techerinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='testdatetime',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='testschedule',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='testsite',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
    ]
