# Generated by Django 2.2.6 on 2019-10-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191021_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='bithday',
            field=models.CharField(max_length=50, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='students',
            name='enrollment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='入学时间'),
        ),
    ]
