# Generated by Django 2.2.6 on 2019-10-24 15:52

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191021_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='score',
            field=computed_property.fields.ComputedFloatField(compute_from='caculate_it', editable=False),
        ),
    ]
