# Generated by Django 2.2.6 on 2019-10-24 16:14

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20191024_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='bithday',
            field=computed_property.fields.ComputedCharField(compute_from='computer_bithday', editable=False, max_length=50, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='students',
            name='score',
            field=computed_property.fields.ComputedFloatField(compute_from='caculate_it', editable=False, verbose_name='分数'),
        ),
    ]
