# Generated by Django 2.2.6 on 2019-10-24 16:16

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191024_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='bithday',
            field=computed_property.fields.ComputedCharField(compute_from='computer_bithday', editable=False, max_length=30, null=True, verbose_name='出生日期'),
        ),
    ]
