# Generated by Django 2.2.6 on 2019-10-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191024_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='genda',
            new_name='gender',
        ),
    ]
