# Generated by Django 2.2.6 on 2019-10-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191024_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techerinfo',
            old_name='techerGenda',
            new_name='techerGender',
        ),
    ]
