# Generated by Django 2.2.6 on 2019-10-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191024_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Basketballdribbling',
            field=models.FloatField(default=0, verbose_name='篮球运球(秒)'),
        ),
        migrations.AddField(
            model_name='students',
            name='Gripstrengthbodymassindex',
            field=models.IntegerField(default=0, verbose_name='握力体重指数'),
        ),
        migrations.AddField(
            model_name='students',
            name='Soccerdribbling',
            field=models.FloatField(default=0, verbose_name='篮球运球(秒)'),
        ),
        migrations.AddField(
            model_name='students',
            name='StepTest',
            field=models.IntegerField(default=0, verbose_name='台阶试验'),
        ),
        migrations.AddField(
            model_name='students',
            name='ropeskipping',
            field=models.IntegerField(default=0, verbose_name='跳绳'),
        ),
        migrations.AddField(
            model_name='students',
            name='throwingsolidball',
            field=models.FloatField(default=0, verbose_name='掷实心球'),
        ),
        migrations.AlterField(
            model_name='students',
            name='stature',
            field=models.FloatField(default=0, verbose_name='身高'),
        ),
    ]
