# Generated by Django 2.2.6 on 2019-10-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20191024_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='性别'),
        ),
    ]
