# Generated by Django 2.2.6 on 2019-10-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20191024_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='techerinfo',
            name='techerGender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别'),
        ),
    ]
