# Generated by Django 2.2.6 on 2019-10-25 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20191024_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='Basketballdribbling',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Gripstrengthbodymassindex',
        ),
        migrations.RemoveField(
            model_name='students',
            name='Soccerdribbling',
        ),
        migrations.RemoveField(
            model_name='students',
            name='StepTest',
        ),
        migrations.RemoveField(
            model_name='students',
            name='ropeskipping',
        ),
        migrations.RemoveField(
            model_name='students',
            name='throwingsolidball',
        ),
    ]
