# Generated by Django 2.2.6 on 2019-10-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20191025_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemWeight',
            fields=[
                ('id', models.FloatField(auto_created=True, primary_key=True, serialize=False, verbose_name='序号')),
                ('BMI', models.FloatField(default=0, verbose_name='体重指数BMI')),
                ('lungcapacity', models.FloatField(default=0, verbose_name='肺活量')),
                ('fiftymeter', models.FloatField(default=0, verbose_name='50米跑')),
                ('sitandreach', models.FloatField(default=0, verbose_name='坐位体前屈')),
                ('standingbroadjump', models.FloatField(default=0, verbose_name='立定跳远')),
                ('pull_ups', models.FloatField(default=0, verbose_name='引体向上')),
                ('Oneminutesitups', models.FloatField(default=0, verbose_name='一分钟仰卧起坐')),
                ('middle_distancerun', models.FloatField(default=0, verbose_name='中长跑')),
            ],
            options={
                'verbose_name': '单项指标与权重',
                'verbose_name_plural': '单项指标与权重',
            },
        ),
    ]
