# Generated by Django 2.2.6 on 2019-10-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20191025_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMITestNormals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('classtype', models.CharField(default=0, max_length=10, verbose_name='等级')),
                ('ItemScore', models.IntegerField(default=0, verbose_name='单项分支')),
                ('male', models.CharField(default='0:0', max_length=50, verbose_name='BMI男范围')),
                ('female', models.CharField(default='0:0', max_length=50, verbose_name='BMI女范围')),
            ],
            options={
                'verbose_name': '体重指数（BMI）单项评分表',
                'verbose_name_plural': '体重指数（BMI）单项评分表',
            },
        ),
        migrations.CreateModel(
            name='FiftymeterTestNormal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('classtype', models.CharField(default=0, max_length=10, verbose_name='等级')),
                ('ItemScore', models.IntegerField(default=0, verbose_name='单项分支')),
                ('malefirst', models.FloatField(default=0, verbose_name='大一大二指标男')),
                ('maleSecond', models.FloatField(default=0, verbose_name='大三大四指标男')),
                ('femalefirst', models.FloatField(default=0, verbose_name='大一大二指标女')),
                ('femaleSecond', models.FloatField(default=0, verbose_name='大三大四指标女')),
            ],
            options={
                'verbose_name': '50米跑单项评分表（单位：秒）',
                'verbose_name_plural': '50米跑单项评分表（单位：秒）',
            },
        ),
        migrations.CreateModel(
            name='LungCapacityTestNormal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('classtype', models.CharField(default=0, max_length=10, verbose_name='等级')),
                ('ItemScore', models.IntegerField(default=0, verbose_name='单项分支')),
                ('malefirst', models.IntegerField(default=0, verbose_name='大一大二指标男')),
                ('maleSecond', models.IntegerField(default=0, verbose_name='大三大四指标男')),
                ('femalefirst', models.IntegerField(default=0, verbose_name='大一大二指标女')),
                ('femaleSecond', models.IntegerField(default=0, verbose_name='大三大四指标女')),
            ],
            options={
                'verbose_name': '肺活量单项评分表（单位：毫升）',
                'verbose_name_plural': '肺活量单项评分表（单位：毫升）',
            },
        ),
        migrations.CreateModel(
            name='MiddleDistanceRunPlusTestNormal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('classtype', models.CharField(default=0, max_length=10, verbose_name='等级')),
                ('ItemScore', models.IntegerField(default=0, verbose_name='单项分支')),
                ('malefirst', models.FloatField(default=0, verbose_name='大一大二指标男')),
                ('maleSecond', models.FloatField(default=0, verbose_name='大三大四指标男')),
                ('femalefirst', models.FloatField(default=0, verbose_name='大一大二指标女')),
                ('femaleSecond', models.FloatField(default=0, verbose_name='大三大四指标女')),
            ],
            options={
                'verbose_name': '男生1000米跑、女生800米评分表（单位：分·秒）',
                'verbose_name_plural': '男生1000米跑、女生800米评分表（单位：分·秒）',
            },
        ),
        migrations.CreateModel(
            name='MiddleDistanceRunTestNormal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('classtype', models.CharField(default=0, max_length=10, verbose_name='等级')),
                ('ItemScore', models.IntegerField(default=0, verbose_name='单项分支')),
                ('malefirst', models.FloatField(default=0, verbose_name='大一大二指标男')),
                ('maleSecond', models.FloatField(default=0, verbose_name='大三大四指标男')),
                ('femalefirst', models.FloatField(default=0, verbose_name='大一大二指标女')),
                ('femaleSecond', models.FloatField(default=0, verbose_name='大三大四指标女')),
            ],
            options={
                'verbose_name': '男生1000米、女生800米耐力跑单项评分表（单位：分·秒）',
                'verbose_name_plural': '男生1000米、女生800米耐力跑单项评分表（单位：分·秒）',
            },
        ),
        migrations.CreateModel(
            name='OneMinuteSitupsAndPullUpPlusNormal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('classtype', models.CharField(default=0, max_length=10, verbose_name='等级')),
                ('ItemScore', models.IntegerField(default=0, verbose_name='单项分支')),
                ('malefirst', models.FloatField(default=0, verbose_name='大一大二指标男')),
                ('maleSecond', models.FloatField(default=0, verbose_name='大三大四指标男')),
                ('femalefirst', models.FloatField(default=0, verbose_name='大一大二指标女')),
                ('femaleSecond', models.FloatField(default=0, verbose_name='大三大四指标女')),
            ],
            options={
                'verbose_name': '男生引体向上、女生仰卧起坐评分表（单位：次）',
                'verbose_name_plural': '男生引体向上、女生仰卧起坐评分表（单位：次）',
            },
        ),
        migrations.CreateModel(
            name='OneMinuteSitupsAndPullUpTestNormal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('classtype', models.CharField(default=0, max_length=10, verbose_name='等级')),
                ('ItemScore', models.IntegerField(default=0, verbose_name='单项分支')),
                ('malefirst', models.FloatField(default=0, verbose_name='大一大二指标男')),
                ('maleSecond', models.FloatField(default=0, verbose_name='大三大四指标男')),
                ('femalefirst', models.FloatField(default=0, verbose_name='大一大二指标女')),
                ('femaleSecond', models.FloatField(default=0, verbose_name='大三大四指标女')),
            ],
            options={
                'verbose_name': '男生引体向上、女生一分钟仰卧起坐评分表（单位：次）',
                'verbose_name_plural': '男生引体向上、女生一分钟仰卧起坐评分表（单位：次）',
            },
        ),
        migrations.CreateModel(
            name='SitandReachTestNoraml',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('classtype', models.CharField(default=0, max_length=10, verbose_name='等级')),
                ('ItemScore', models.IntegerField(default=0, verbose_name='单项分支')),
                ('malefirst', models.FloatField(default=0, verbose_name='大一大二指标男')),
                ('maleSecond', models.FloatField(default=0, verbose_name='大三大四指标男')),
                ('femalefirst', models.FloatField(default=0, verbose_name='大一大二指标女')),
                ('femaleSecond', models.FloatField(default=0, verbose_name='大三大四指标女')),
            ],
            options={
                'verbose_name': '坐位体前屈单项评分表（单位：厘米）',
                'verbose_name_plural': '坐位体前屈单项评分表（单位：厘米）',
            },
        ),
        migrations.CreateModel(
            name='StandingBroadJumpTestNormal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('classtype', models.CharField(default=0, max_length=10, verbose_name='等级')),
                ('ItemScore', models.IntegerField(default=0, verbose_name='单项分支')),
                ('malefirst', models.FloatField(default=0, verbose_name='大一大二指标男')),
                ('maleSecond', models.FloatField(default=0, verbose_name='大三大四指标男')),
                ('femalefirst', models.FloatField(default=0, verbose_name='大一大二指标女')),
                ('femaleSecond', models.FloatField(default=0, verbose_name='大三大四指标女')),
            ],
            options={
                'verbose_name': '立定跳远单项评分表（单位：厘米）',
                'verbose_name_plural': '立定跳远单项评分表（单位：厘米）',
            },
        ),
        migrations.DeleteModel(
            name='BML',
        ),
    ]
