# Generated by Django 2.2.6 on 2019-10-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20191025_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='middledistancerunplustestnormal',
            options={'verbose_name': '男生1000米跑、女生800米加分表（单位：分·秒）', 'verbose_name_plural': '男生1000米跑、女生800米加分表（单位：分·秒）'},
        ),
        migrations.AlterModelOptions(
            name='oneminutesitupsandpullupplusnormal',
            options={'verbose_name': '男生引体向上、女生仰卧起坐加分表（单位：次）', 'verbose_name_plural': '男生引体向上、女生仰卧起坐加分表（单位：次）'},
        ),
    ]
