# Generated by Django 2.2.6 on 2019-10-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20191025_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmitestnormals',
            name='ItemScore',
            field=models.IntegerField(default=0, verbose_name='单项分值'),
        ),
        migrations.AlterField(
            model_name='fiftymetertestnormal',
            name='ItemScore',
            field=models.IntegerField(default=0, verbose_name='单项分值'),
        ),
        migrations.AlterField(
            model_name='lungcapacitytestnormal',
            name='ItemScore',
            field=models.IntegerField(default=0, verbose_name='单项分值'),
        ),
        migrations.AlterField(
            model_name='middledistancerunplustestnormal',
            name='ItemScore',
            field=models.IntegerField(default=0, verbose_name='单项分值'),
        ),
        migrations.AlterField(
            model_name='middledistanceruntestnormal',
            name='ItemScore',
            field=models.IntegerField(default=0, verbose_name='单项分值'),
        ),
        migrations.AlterField(
            model_name='oneminutesitupsandpullupplusnormal',
            name='ItemScore',
            field=models.IntegerField(default=0, verbose_name='单项分值'),
        ),
        migrations.AlterField(
            model_name='oneminutesitupsandpulluptestnormal',
            name='ItemScore',
            field=models.IntegerField(default=0, verbose_name='单项分值'),
        ),
        migrations.AlterField(
            model_name='sitandreachtestnoraml',
            name='ItemScore',
            field=models.IntegerField(default=0, verbose_name='单项分值'),
        ),
        migrations.AlterField(
            model_name='standingbroadjumptestnormal',
            name='ItemScore',
            field=models.IntegerField(default=0, verbose_name='单项分值'),
        ),
    ]
