# Generated by Django 2.2.6 on 2019-10-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20191025_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middledistancerunplustestnormal',
            name='femaleSecond',
            field=models.CharField(default=0, max_length=10, verbose_name='大三大四指标女'),
        ),
        migrations.AlterField(
            model_name='middledistancerunplustestnormal',
            name='femalefirst',
            field=models.CharField(default=0, max_length=10, verbose_name='大一大二指标女'),
        ),
        migrations.AlterField(
            model_name='middledistancerunplustestnormal',
            name='maleSecond',
            field=models.CharField(default=0, max_length=10, verbose_name='大三大四指标男'),
        ),
        migrations.AlterField(
            model_name='middledistancerunplustestnormal',
            name='malefirst',
            field=models.CharField(default=0, max_length=10, verbose_name='大一大二指标男'),
        ),
        migrations.AlterField(
            model_name='middledistanceruntestnormal',
            name='femaleSecond',
            field=models.CharField(default=0, max_length=10, verbose_name='大三大四指标女'),
        ),
        migrations.AlterField(
            model_name='middledistanceruntestnormal',
            name='femalefirst',
            field=models.CharField(default=0, max_length=10, verbose_name='大一大二指标女'),
        ),
        migrations.AlterField(
            model_name='middledistanceruntestnormal',
            name='maleSecond',
            field=models.CharField(default=0, max_length=10, verbose_name='大三大四指标男'),
        ),
        migrations.AlterField(
            model_name='middledistanceruntestnormal',
            name='malefirst',
            field=models.CharField(default=0, max_length=10, verbose_name='大一大二指标男'),
        ),
    ]
