# Generated by Django 2.2.6 on 2019-10-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20191025_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='middle_distancerun',
            field=models.CharField(default=0, max_length=10, verbose_name='中长跑'),
        ),
    ]
