# Generated by Django 2.2.6 on 2019-10-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20191025_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneminutesitupsandpullupplusnormal',
            name='femaleSecond',
            field=models.IntegerField(default=0, verbose_name='大三大四指标女'),
        ),
        migrations.AlterField(
            model_name='oneminutesitupsandpullupplusnormal',
            name='femalefirst',
            field=models.IntegerField(default=0, verbose_name='大一大二指标女'),
        ),
        migrations.AlterField(
            model_name='oneminutesitupsandpullupplusnormal',
            name='maleSecond',
            field=models.IntegerField(default=0, verbose_name='大三大四指标男'),
        ),
        migrations.AlterField(
            model_name='oneminutesitupsandpullupplusnormal',
            name='malefirst',
            field=models.IntegerField(default=0, verbose_name='大一大二指标男'),
        ),
        migrations.AlterField(
            model_name='oneminutesitupsandpulluptestnormal',
            name='femaleSecond',
            field=models.IntegerField(default=0, verbose_name='大三大四指标女'),
        ),
        migrations.AlterField(
            model_name='oneminutesitupsandpulluptestnormal',
            name='femalefirst',
            field=models.IntegerField(default=0, verbose_name='大一大二指标女'),
        ),
        migrations.AlterField(
            model_name='oneminutesitupsandpulluptestnormal',
            name='maleSecond',
            field=models.IntegerField(default=0, verbose_name='大三大四指标男'),
        ),
        migrations.AlterField(
            model_name='oneminutesitupsandpulluptestnormal',
            name='malefirst',
            field=models.IntegerField(default=0, verbose_name='大一大二指标男'),
        ),
    ]
