# Generated by Django 2.2.6 on 2019-10-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20191025_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gradeclass',
            field=models.CharField(max_length=20, verbose_name='年级'),
        ),
    ]
