# Generated by Django 2.2.6 on 2019-10-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20191025_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmitestnormals',
            name='female',
            field=models.FloatField(default='0.0', verbose_name='BMI女范围'),
        ),
        migrations.AlterField(
            model_name='bmitestnormals',
            name='male',
            field=models.FloatField(default='0.s0', verbose_name='BMI男范围'),
        ),
    ]
