# Generated by Django 2.2.6 on 2019-10-26 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20191025_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middledistanceruntestnormal',
            name='femaleSecond',
            field=models.FloatField(default=0, verbose_name='大三大四指标女'),
        ),
        migrations.AlterField(
            model_name='middledistanceruntestnormal',
            name='femalefirst',
            field=models.FloatField(default=0, verbose_name='大一大二指标女'),
        ),
        migrations.AlterField(
            model_name='middledistanceruntestnormal',
            name='maleSecond',
            field=models.FloatField(default=0, verbose_name='大三大四指标男'),
        ),
        migrations.AlterField(
            model_name='middledistanceruntestnormal',
            name='malefirst',
            field=models.FloatField(default=0, verbose_name='大一大二指标男'),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_distancerun',
            field=models.FloatField(default=0, verbose_name='中长跑'),
        ),
    ]
